# This is a basic workflow to help you get started with Actions

name: pushAfterMerge

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: ubuntu-18.04
    env:
      DEPLOY_TO: ${{ 'blue' }}
    steps:
      - name: print deploy target to log
        run: echo "$DEPLOY_TO"
      - name: check out the repo
        uses: actions/checkout@v2
      - name: deploy blue
        uses: citizen-of-planet-earth/cf-cli-action@master
        if: env.DEDPLOY_TO == 'blue'
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          command: push gettingstarted-tim-blue
      - name: map route to blue
        uses: citizen-of-planet-earth/cf-cli-action@master
        if: env.DEDPLOY_TO == 'blue'
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          command: map-route gettingstarted-tim-blue cap.explore.suse.dev --hostname gettingstarted-tim 
      - name: unmap green route
        uses: citizen-of-planet-earth/cf-cli-action@master
        if: env.DEPLOY_TO == 'blue'
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          command: unmap-route gettingstarted-tim-green cap.explore.suse.dev --hostname gettingstarted-tim 
      - name: deploy green
        uses: citizen-of-planet-earth/cf-cli-action@master
#        if: env.DEPLOY_TO == 'green'
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          command: push gettingstarted-tim-green
      - name: map route to green
        uses: citizen-of-planet-earth/cf-cli-action@master
#        if: env.DEPLOY_TO == 'green'
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          command: map-route gettingstarted-tim-green cap.explore.suse.dev --hostname gettingstarted-tim 
      - name: unmap blue route
        uses: citizen-of-planet-earth/cf-cli-action@master
#        if: env.DEPLOY_TO == 'green'
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          command: unmap-route gettingstarted-tim-blue cap.explore.suse.dev --hostname gettingstarted-tim 
